### ISSUE TITLE
AttributeError: 'Package' object has no attribute 'all'

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#259]
Hello, 

As the ultimate test and demo for people, I'm trying to generate the whole CPython standard Library API docs. 

And I ran into this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pydoctor", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/pydoctor/driver.py", line 308, in main
    system.process()
  File "/usr/local/lib/python3.8/site-packages/pydoctor/model.py", line 726, in process
    self.processModule(mod)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/model.py", line 710, in processModule
    builder.processModuleAST(ast, mod)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 639, in processModuleAST
    self.ModuleVistor(self, mod).visit(ast)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 78, in visit_Module
    self.default(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 67, in default
    self.visit(child)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 169, in visit_ImportFrom
    mod = self.system.getProcessedModule(modname)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/model.py", line 690, in getProcessedModule
    return self.getProcessedModule(modname + '.__init__').parent
  File "/usr/local/lib/python3.8/site-packages/pydoctor/model.py", line 695, in getProcessedModule
    self.processModule(mod)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/model.py", line 710, in processModule
    builder.processModuleAST(ast, mod)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 639, in processModuleAST
    self.ModuleVistor(self, mod).visit(ast)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 78, in visit_Module
    self.default(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 67, in default
    self.visit(child)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 169, in visit_ImportFrom
    mod = self.system.getProcessedModule(modname)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/model.py", line 695, in getProcessedModule
    self.processModule(mod)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/model.py", line 710, in processModule
    builder.processModuleAST(ast, mod)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 639, in processModuleAST
    self.ModuleVistor(self, mod).visit(ast)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 78, in visit_Module
    self.default(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 67, in default
    self.visit(child)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 363, in visit
    return visitor(node)
  File "/usr/local/lib/python3.8/site-packages/pydoctor/astbuilder.py", line 184, in visit_ImportFrom
    if mod.all is not None:
AttributeError: 'Package' object has no attribute 'all'
```

I'm running Python 3.8, trying to document the '3.8' tag of https://github.com/python/cpython

The PyDoctor command is 
```
bash -c "pydoctor $(ls Lib/ | awk '{ print $0 }' | sed 's/^/--add-package=Lib\//' | sed 's/--add-package=Lib\/site-packages//' | tr '\n' ' ') --project-name='Python 3.8 Standard Library' --html-viewsource-base=https://github.com/python/cpython/tree/3.8 --make-html --html-output=apidocs --project-base-dir="$(pwd)" --docformat=restructuredtext --intersphinx=https://docs.python.org/3/objects.inv"
```

I understand in #255 that `--add-package` and `--add-module` are actually the same thing, so I didn't use `--add-module`.

**Comment by adiroiban** [comment]
I was able to reproduce it...

It looks like the packages raising this issue are ctypes and tkinter

baby steps to reproduce it from a venv which has pydoctor :) 

```
git clone https://github.com/python/cpython.git
cd cpython
pydoctor  --add-package=Lib/ctypes --project-base-dir=.
pydoctor  --add-package=Lib/tkinter --project-base-dir=.
```

After skipping these modules I got other errors... but those errors should be reported in separate issues.

Thanks for the report

**Comment by mthuurne** [comment]
The problem with `ctypes` seems to be a confusion between package and module: class `Module` has an `all` attribute, while class `Package` does not. This is the kind of bug we can avoid by increasing mypy coverage.

**Comment by mthuurne** [comment]
The generation of the CPython API docs no longer crashes. It is available now in the `cpython-apidocs` tox env.

It does generate a lot of warnings and I don't know how many of those are mistakes in CPython's docstrings and how many are shortcomings of pydoctor.
