### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by tristanlatr** [twisted/pydoctor#376]
I'm trying to generate the [Natural Language Toolkit](https://github.com/nltk/nltk) API docs, they used to do it with Epytext.

I'm running into an `AssertionError`, I believe we should not run into those right?

Also, the traceback is not consistent from one call to another so here are two:

```
% git clone git@github.com:tristanlatr/nltk.git
% cd nltk                              
% pydoctor --docformat=plaintext ./nltk
adding directory /Users/tristan/Documents/pydoctor/nltk/nltk
369 modules and packages discovered
Guessing 'nltk' for project name.
32/342 modules processed, 0 warnings
moving 'nltk.lm.models.MLE' into 'nltk.lm.__init__'
moving 'nltk.lm.models.Lidstone' into 'nltk.lm.__init__'
moving 'nltk.lm.models.Laplace' into 'nltk.lm.__init__'
moving 'nltk.lm.models.WittenBellInterpolated' into 'nltk.lm.__init__'
moving 'nltk.lm.models.KneserNeyInterpolated' into 'nltk.lm.__init__'
moving 'nltk.lm.counter.NgramCounter' into 'nltk.lm.__init__'
moving 'nltk.lm.vocabulary.Vocabulary' into 'nltk.lm.__init__'
185/342 modules processed, 0 warnings
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1806: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1811: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1816: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1821: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1826: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1831: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2122: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2123: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2124: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2125: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2126: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2127: Unable to figure out value for __doc__ assignment, maybe too complex
229/342 modules processed, 12 warningsTraceback (most recent call last):
  File "/Users/tristan/.pyenv/versions/3.9.1/bin/pydoctor", line 33, in <module>
    sys.exit(load_entry_point('pydoctor==21.2.2', 'console_scripts', 'pydoctor')())
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/driver.py", line 437, in main
    system.process()
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 956, in process
    self.processModule(mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 941, in processModule
    builder.processModuleAST(ast, mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 1054, in processModuleAST
    self.ModuleVistor(self, mod).visit(mod_ast)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 198, in visit_Module
    self.default(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 187, in default
    self.visit(child)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 299, in visit_ImportFrom
    self._importNames(modname, node.names)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 336, in _importNames
    mod = self.system.getProcessedModule(modname)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 920, in getProcessedModule
    return self.getProcessedModule(modname + '.__init__')
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 925, in getProcessedModule
    self.processModule(mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 941, in processModule
    builder.processModuleAST(ast, mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 1054, in processModuleAST
    self.ModuleVistor(self, mod).visit(mod_ast)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 198, in visit_Module
    self.default(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 187, in default
    self.visit(child)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 299, in visit_ImportFrom
    self._importNames(modname, node.names)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 336, in _importNames
    mod = self.system.getProcessedModule(modname)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 925, in getProcessedModule
    self.processModule(mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 941, in processModule
    builder.processModuleAST(ast, mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 1054, in processModuleAST
    self.ModuleVistor(self, mod).visit(mod_ast)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 198, in visit_Module
    self.default(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 187, in default
    self.visit(child)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 299, in visit_ImportFrom
    self._importNames(modname, node.names)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/astbuilder.py", line 336, in _importNames
    mod = self.system.getProcessedModule(modname)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 920, in getProcessedModule
    return self.getProcessedModule(modname + '.__init__')
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 925, in getProcessedModule
    self.processModule(mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 944, in processModule
    assert head == mod.fullName()
AssertionError
% pydoctor --docformat=plaintext ./nltk
adding directory /Users/tristan/Documents/pydoctor/nltk/nltk
369 modules and packages discovered
Guessing 'nltk' for project name.
36/342 modules processed, 0 warnings
moving 'nltk.lm.models.MLE' into 'nltk.lm.__init__'
moving 'nltk.lm.models.Lidstone' into 'nltk.lm.__init__'
moving 'nltk.lm.models.Laplace' into 'nltk.lm.__init__'
moving 'nltk.lm.models.WittenBellInterpolated' into 'nltk.lm.__init__'
moving 'nltk.lm.models.KneserNeyInterpolated' into 'nltk.lm.__init__'
moving 'nltk.lm.counter.NgramCounter' into 'nltk.lm.__init__'
moving 'nltk.lm.vocabulary.Vocabulary' into 'nltk.lm.__init__'
143/342 modules processed, 0 warnings
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1806: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1811: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1816: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1821: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1826: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:1831: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2122: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2123: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2124: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2125: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2126: Unable to figure out value for __doc__ assignment, maybe too complex
/Users/tristan/Documents/pydoctor/nltk/nltk/corpus/reader/wordnet.py:2127: Unable to figure out value for __doc__ assignment, maybe too complex
227/342 modules processed, 12 warningsTraceback (most recent call last):
  File "/Users/tristan/.pyenv/versions/3.9.1/bin/pydoctor", line 33, in <module>
    sys.exit(load_entry_point('pydoctor==21.2.2', 'console_scripts', 'pydoctor')())
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/driver.py", line 437, in main
    system.process()
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 956, in process
    self.processModule(mod)
  File "/Users/tristan/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pydoctor/model.py", line 944, in processModule
    assert head == mod.fullName()
AssertionError
```

**Comment by mthuurne** [comment]
I can reproduce the problem on the "master" branch, but not on "package-is-a-module". So merging #360 should fix this.
