### ISSUE TITLE
pip install pydoctor fails to pull in dependencies

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#55]
robertc@lifeless-64:~$ mkvirtualenv extras
New python executable in extras/bin/python
Installing setuptools............done.
Installing pip...............done.
virtualenvwrapper.user_scripts creating /home/robertc/.virtualenvs/extras/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/robertc/.virtualenvs/extras/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/robertc/.virtualenvs/extras/bin/preactivate
virtualenvwrapper.user_scripts creating /home/robertc/.virtualenvs/extras/bin/postactivate
virtualenvwrapper.user_scripts creating /home/robertc/.virtualenvs/extras/bin/get_env_details
(extras)robertc@lifeless-64:~$ cd source/unittest/extras/
(extras)robertc@lifeless-64:~/source/unittest/extras$ pip install pydoctor
Downloading/unpacking pydoctor
  Downloading pydoctor-0.4.tar.gz (81kB): 81kB downloaded
  Running setup.py egg_info for package pydoctor

    warning: no directories found matching 'pydoctor/templates/'
Installing collected packages: pydoctor
  Running setup.py install for pydoctor
    changing mode of build/scripts-2.7/pydoctor from 664 to 775
    /home/robertc/.virtualenvs/extras/bin/python -O /tmp/tmpZbEqKM.py
    removing /tmp/tmpZbEqKM.py

    warning: no directories found matching 'pydoctor/templates/'
    changing mode of /home/robertc/.virtualenvs/extras/bin/pydoctor to 775
Successfully installed pydoctor
Cleaning up...
(extras)robertc@lifeless-64:~/source/unittest/extras$ make apidocs
# pydoctor emits deprecation warnings under Ubuntu 10.10 LTS
PYTHONWARNINGS='ignore::DeprecationWarning' \
                pydoctor --make-html --add-package extras \
                --docformat=restructuredtext --project-name=extras \
                --project-url=https://launchpad.net/extras
adding directory /home/robertc/source/unittest/extras/extras
5 modules and packages discovered
Traceback (most recent call last):
  File "/home/robertc/.virtualenvs/extras/bin/pydoctor", line 12, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/driver.py", line 330, in main
    system.process()
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/model.py", line 713, in process
    self.processModule(mod)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/model.py", line 697, in processModule
    builder.processModuleAST(ast, mod)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 391, in processModuleAST
    visitor.walk(ast, self.ModuleVistor(self, mod))
  File "/usr/lib/python2.7/compiler/visitor.py", line 106, in walk
    walker.preorder(tree, visitor)
  File "/usr/lib/python2.7/compiler/visitor.py", line 63, in preorder
    self.dispatch(tree, *args) # XXX *args make sense?
  File "/usr/lib/python2.7/compiler/visitor.py", line 57, in dispatch
    return meth(node, *args)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 81, in visitModule
    self.default(node)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 75, in default
    self.visit(child)
  File "/usr/lib/python2.7/compiler/visitor.py", line 57, in dispatch
    return meth(node, *args)
  File "/usr/lib/python2.7/compiler/visitor.py", line 40, in default
    self.dispatch(child, *args)
  File "/usr/lib/python2.7/compiler/visitor.py", line 57, in dispatch
    return meth(node, *args)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 148, in visitFrom
    mod = self.system.getProcessedModule(modname)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/model.py", line 677, in getProcessedModule
    return self.getProcessedModule(modname + '.__init__')
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/model.py", line 682, in getProcessedModule
    self.processModule(mod)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/model.py", line 697, in processModule
    builder.processModuleAST(ast, mod)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 391, in processModuleAST
    visitor.walk(ast, self.ModuleVistor(self, mod))
  File "/usr/lib/python2.7/compiler/visitor.py", line 106, in walk
    walker.preorder(tree, visitor)
  File "/usr/lib/python2.7/compiler/visitor.py", line 63, in preorder
    self.dispatch(tree, *args) # XXX *args make sense?
  File "/usr/lib/python2.7/compiler/visitor.py", line 57, in dispatch
    return meth(node, *args)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 81, in visitModule
    self.default(node)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 75, in default
    self.visit(child)
  File "/usr/lib/python2.7/compiler/visitor.py", line 57, in dispatch
    return meth(node, *args)
  File "/usr/lib/python2.7/compiler/visitor.py", line 40, in default
    self.dispatch(child, *args)
  File "/usr/lib/python2.7/compiler/visitor.py", line 57, in dispatch
    return meth(node, *args)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 265, in visitFunction
    func = self.builder.pushFunction(node.name, node.doc)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 377, in pushFunction
    return self._push(self.system.Function, name, docstring)
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/astbuilder.py", line 337, in _push
    from pydoctor import epydoc2stan
  File "/home/robertc/.virtualenvs/extras/local/lib/python2.7/site-packages/pydoctor/epydoc2stan.py", line 7, in <module>
    from nevow import tags
ImportError: No module named nevow
make: *** [apidocs] Error 1

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-12-13T08:30:43Z
 * owner: lifeless
 * the launchpad url was https://bugs.launchpad.net/bugs/1089796

**Comment by mwhudson** [comment]
(by mwhudson)
No surprise there, the dependencies aren't listed in setup.py (do I need
to use setuptools/distribute for this to work?)

**Comment by mwhudson** [comment]
(by lifeless)
I am not entirely sure. lets say 'yes'.

**Comment by mwhudson** [comment]
(by mwhudson)
It turns out that pydoctor's main dependency, Nevow, also does not include install_requires and it turns out that doing anything in pydoctor is futile (even if I declare nevow's dependencies in pydoctor's setup.py, pip still tries to egg-info nevow too early).

I filed https://bugs.launchpad.net/divmod.org/+bug/1091055 for the nevow problem.

**Comment by mwhudson** [comment]
(by mwhudson)
Oh, so a fix for this would be to move to twisted.web.template which would probably be a good idea anyway (https://bugs.launchpad.net/pydoctor/+bug/964803) but is sadly not trivial.

**Comment by mwhudson** [comment]
(by lifeless)
have you tried putting nevow's dependencies first in setup.py?

**Comment by mwhudson** [comment]
(by mwhudson)
Robert Collins <email address hidden> writes:

> have you tried putting nevow's dependencies first in setup.py?

Yes.  I suspect the problem is that Twisted is quite a lot bigger than
Nevow so the download of Nevow finishes first (I haven't actually
checked the pip source because I didn't want to feel ill today).

**Comment by mwhudson** [comment]
(by lifeless)
On Mon, Dec 17, 2012 at 8:31 PM, Michael Hudson-Doyle
<email address hidden> wrote:
> Robert Collins <email address hidden> writes:
>
>> have you tried putting nevow's dependencies first in setup.py?
>
> Yes.  I suspect the problem is that Twisted is quite a lot bigger than
> Nevow so the download of Nevow finishes first (I haven't actually
> checked the pip source because I didn't want to feel ill today).

Odd!. pip is single threaded non-async AFAIK.

**Comment by mwhudson** [comment]
(by mwhudson)
Robert Collins <email address hidden> writes:

> On Mon, Dec 17, 2012 at 8:31 PM, Michael Hudson-Doyle
> <email address hidden> wrote:
>> Robert Collins <email address hidden> writes:
>>
>>> have you tried putting nevow's dependencies first in setup.py?
>>
>> Yes.  I suspect the problem is that Twisted is quite a lot bigger than
>> Nevow so the download of Nevow finishes first (I haven't actually
>> checked the pip source because I didn't want to feel ill today).
>
> Odd!. pip is single threaded non-async AFAIK.

It does some stuff in threads at least:
https://github.com/pypa/pip/blob/develop/pip/index.py#L229

Although that looks like maybe it's not used for downloading actual
packages.  In any case: I tried both install_requires=["Twisted",
"Nevow"] and install_requires=["Nevow", "Twisted"] and neither worked.

Cheers,
mwh

**Comment by mwhudson** [comment]
(by mithrandi)
The field you want is setup_requires, not install_requires. Unfortunately this field is somewhat useless because pip etc. have to run setup.py in order to determine the value of this field, but running setup.py will likely fail due to the missing packages...

If I'm not mistaken, packages in install_requires will not be available at the time setup.py is run, regardless of which order pip downloads / installs them in (due to the sandboxing it does).

**Comment by mwhudson** [comment]
(by mwhudson)
Tristan Seligmann <email address hidden> writes:

> The field you want is setup_requires, not install_requires.

I want setup_requires in Nevow, not pydoctor :-)  But even that doesn't
actually work.

> Unfortunately this field is somewhat useless because pip etc. have to
> run setup.py in order to determine the value of this field, but running
> setup.py will likely fail due to the missing packages...
>
> If I'm not mistaken, packages in install_requires will not be available
> at the time setup.py is run, regardless of which order pip downloads /
> installs them in (due to the sandboxing it does).

That may be.

It's just all a bit frustrating that:

 pip install twisted
 pip install nevow
 pip install pydoctor

works, but there's nothing I can write in pydoctor's setup.py that will
make just "pip install pydoctor" work.  I think Nevow can be fixed so
that this will work though.

Cheers,
mwh

**Comment by mwhudson** [comment]
(by lifeless)
mwhudson - did you try setup_requires? It would get exported to the PKG_INFO IIRC, and its needs would run before anything else.
so
setup_requires = ['twisted']
install_requires = ['nevow']

should let you stage things.

**Comment by mwhudson** [comment]
(by mwhudson)
Robert Collins <email address hidden> writes:

> mwhudson - did you try setup_requires? It would get exported to the PKG_INFO IIRC, and its needs would run before anything else.
> so
> setup_requires = ['twisted']
> install_requires = ['nevow']
>
> should let you stage things.

I hadn't, but that doesn't work either :(  (it seems that the twisted
that gets installed because of the setup_requires is not available when
nevow gets egg-info'ed)

**Comment by mwhudson** [comment]
(by lifeless)
aieee

On Tue, Dec 18, 2012 at 10:28 PM, Michael Hudson-Doyle
<email address hidden> wrote:
> Robert Collins <email address hidden> writes:
>
>> mwhudson - did you try setup_requires? It would get exported to the PKG_INFO IIRC, and its needs would run before anything else.
>> so
>> setup_requires = ['twisted']
>> install_requires = ['nevow']
>>
>> should let you stage things.
>
> I hadn't, but that doesn't work either :(  (it seems that the twisted
> that gets installed because of the setup_requires is not available when
> nevow gets egg-info'ed)
>
> --
> You received this bug notification because you are subscribed to the bug
> report.
> https://bugs.launchpad.net/bugs/1089796
>
> Title:
>   pip install pydoctor fails to pull in dependencies
>
> To manage notifications about this bug go to:
> https://bugs.launchpad.net/pydoctor/+bug/1089796/+subscriptions



-- 
Robert Collins <email address hidden>
Distinguished Technologist
HP Cloud Services

**Comment by mwhudson** [comment]
(by mwhudson)
Fixed by not depending on nevow any more.

**Comment by mwhudson** [comment]
(by lifeless)
\o/
