### ISSUE TITLE
22.5.0: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [twisted/pydoctor#556]
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

Here is pytest output:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --import-mode=importlib
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0, configfile: setup.cfg, testpaths: pydoctor/test
plugins: cov-3.0.0, hypothesis-6.41.0
collected 727 items

pydoctor/test/test_astbuilder.py ................................................................................................................................... [ 18%]
.................................................................................................................................................................... [ 40%]
..............                                                                                                                                                       [ 42%]
pydoctor/test/test_colorize.py .....                                                                                                                                 [ 43%]
pydoctor/test/test_commandline.py ..................                                                                                                                 [ 45%]
pydoctor/test/test_configparser.py ......                                                                                                                            [ 46%]
pydoctor/test/test_cyclic_imports_base_classes.py F                                                                                                                  [ 46%]
pydoctor/test/test_epydoc2stan.py ........xxx.......................................................                                                                 [ 55%]
pydoctor/test/test_model.py ..FF..........s......                                                                                                                    [ 58%]
pydoctor/test/test_napoleon_docstring.py ......................................................                                                                      [ 66%]
pydoctor/test/test_napoleon_iterators.py .................                                                                                                           [ 68%]
pydoctor/test/test_node2stan.py .                                                                                                                                    [ 68%]
pydoctor/test/test_options.py .........                                                                                                                              [ 69%]
pydoctor/test/test_packages.py ............                                                                                                                          [ 71%]
pydoctor/test/test_qnmatch.py ......                                                                                                                                 [ 72%]
pydoctor/test/test_sphinx.py .............................                                                                                                           [ 76%]
pydoctor/test/test_templatewriter.py ................................                                                                                                [ 80%]
pydoctor/test/test_type_fields.py .........                                                                                                                          [ 81%]
pydoctor/test/test_utils.py ...............                                                                                                                          [ 83%]
pydoctor/test/test_zopeinterface.py .........................                                                                                                        [ 87%]
pydoctor/test/epydoc/epytext.doctest .                                                                                                                               [ 87%]
pydoctor/test/epydoc/restructuredtext.doctest .                                                                                                                      [ 87%]
pydoctor/test/epydoc/test_epytext.py ....                                                                                                                            [ 88%]
pydoctor/test/epydoc/test_epytext2html.py ...........                                                                                                                [ 89%]
pydoctor/test/epydoc/test_epytext2node.py .                                                                                                                          [ 89%]
pydoctor/test/epydoc/test_google_numpy.py .....                                                                                                                      [ 90%]
pydoctor/test/epydoc/test_parsed_docstrings.py .                                                                                                                     [ 90%]
pydoctor/test/epydoc/test_pyval_repr.py ..................................................                                                                           [ 97%]
pydoctor/test/epydoc/test_restructuredtext.py ..................                                                                                                     [100%]

================================================================================= FAILURES =================================================================================
_____________________________________________________________________ test_cyclic_imports_base_classes _____________________________________________________________________

    def test_cyclic_imports_base_classes() -> None:
        if sys.platform == 'win32':
            # Running this script with the following subprocess call fails on Windows
            # with an ImportError that isn't actually related to what we want to test.
            # So we just skip for Windows.
            return

        process = subprocess.Popen(
            [sys.executable, os.path.basename(__file__)],
            env={'PYTHONHASHSEED': '0'},
            cwd=os.path.dirname(__file__),
        )
>       assert process.wait() == 0
E       assert 1 == 0
E        +  where 1 = <bound method Popen.wait of <subprocess.Popen object at 0x7fcc7a9fb8e0>>()
E        +    where <bound method Popen.wait of <subprocess.Popen object at 0x7fcc7a9fb8e0>> = <subprocess.Popen object at 0x7fcc7a9fb8e0>.wait

pydoctor/test/test_cyclic_imports_base_classes.py:22: AssertionError
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cyclic_imports_base_classes.py", line 26, in <module>
    from test_packages import processPackage, model # type: ignore
  File "/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0/pydoctor/test/test_packages.py", line 5, in <module>
    from pydoctor import model
ModuleNotFoundError: No module named 'pydoctor'
___________________________________________________________________ test_htmlsourcetemplate_auto_detect ____________________________________________________________________

    def test_htmlsourcetemplate_auto_detect() -> None:
        """
        Tests for the recognition of different version control providers
        that uses differents URL templates to point to line numbers.

        Supported templates are::

            Github : {}#L{lineno}
            Bitbucket: {}#lines-{lineno}
            SourceForge : {}#l{lineno}
        """
        cases = [
            ("http://example.org/trac/browser/trunk",
             "http://example.org/trac/browser/trunk/pydoctor/test/testpackages/basic/mod.py#L7"),

            ("https://sourceforge.net/p/epydoc/code/HEAD/tree/trunk/epydoc",
             "https://sourceforge.net/p/epydoc/code/HEAD/tree/trunk/epydoc/pydoctor/test/testpackages/basic/mod.py#l7"),

            ("https://bitbucket.org/user/scripts/src/master",
             "https://bitbucket.org/user/scripts/src/master/pydoctor/test/testpackages/basic/mod.py#lines-7"),
        ]
        for base, var_href in cases:
            options = model.Options.from_args([f'--html-viewsource-base={base}', '--project-base-dir=.'])
            system = model.System(options)

>           processPackage('basic', systemcls=lambda:system)

pydoctor/test/test_model.py:92:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/test/test_packages.py:11: in processPackage
    system.addPackage(testpackages / packname)
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/model.py:997: in addPackage
    package = self.analyzeModule(
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/model.py:893: in analyzeModule
    self.setSourceHref(mod, modpath)
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/model.py:865: in setSourceHref
    relative = source_path.relative_to(projBaseDir).as_posix()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PosixPath('/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/test/testpackages/basic/__init__.py')
other = (PosixPath('/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0'),)
parts = ['/', 'home', 'tkloczko', 'rpmbuild', 'BUILDROOT', 'python-pydoctor-22.5.0-2.fc35.x86_64', ...], drv = '', root = '/'

    def relative_to(self, *other):
        """Return the relative path to another path identified by the passed
        arguments.  If the operation is not possible (because this is not
        a subpath of the other path), raise ValueError.
        """
        # For the purpose of this method, drive and root are considered
        # separate parts, i.e.:
        #   Path('c:/').relative_to('c:')  gives Path('/')
        #   Path('c:/').relative_to('/')   raise ValueError
        if not other:
            raise TypeError("need at least one argument")
        parts = self._parts
        drv = self._drv
        root = self._root
        if root:
            abs_parts = [drv, root] + parts[1:]
        else:
            abs_parts = parts
        to_drv, to_root, to_parts = self._parse_args(other)
        if to_root:
            to_abs_parts = [to_drv, to_root] + to_parts[1:]
        else:
            to_abs_parts = to_parts
        n = len(to_abs_parts)
        cf = self._flavour.casefold_parts
        if (root or drv) if n == 0 else cf(abs_parts[:n]) != cf(to_abs_parts):
            formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
>           raise ValueError("{!r} does not start with {!r}"
                             .format(str(self), str(formatted)))
E           ValueError: '/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/test/testpackages/basic/__init__.py' does not start with '/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0'

/usr/lib64/python3.8/pathlib.py:908: ValueError
______________________________________________________________________ test_htmlsourcetemplate_custom ______________________________________________________________________

    def test_htmlsourcetemplate_custom() -> None:
        """
        The links to source code web pages can be customized via an CLI argument.
        """
        options = model.Options.from_args([
            '--html-viewsource-base=http://example.org/trac/browser/trunk',
            '--project-base-dir=.',
            '--html-viewsource-template={mod_source_href}#n{lineno}'])
        system = model.System(options)

>       processPackage('basic', systemcls=lambda:system)

pydoctor/test/test_model.py:105:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/test/test_packages.py:11: in processPackage
    system.addPackage(testpackages / packname)
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/model.py:997: in addPackage
    package = self.analyzeModule(
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/model.py:893: in analyzeModule
    self.setSourceHref(mod, modpath)
../../BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/model.py:865: in setSourceHref
    relative = source_path.relative_to(projBaseDir).as_posix()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PosixPath('/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/test/testpackages/basic/__init__.py')
other = (PosixPath('/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0'),)
parts = ['/', 'home', 'tkloczko', 'rpmbuild', 'BUILDROOT', 'python-pydoctor-22.5.0-2.fc35.x86_64', ...], drv = '', root = '/'

    def relative_to(self, *other):
        """Return the relative path to another path identified by the passed
        arguments.  If the operation is not possible (because this is not
        a subpath of the other path), raise ValueError.
        """
        # For the purpose of this method, drive and root are considered
        # separate parts, i.e.:
        #   Path('c:/').relative_to('c:')  gives Path('/')
        #   Path('c:/').relative_to('/')   raise ValueError
        if not other:
            raise TypeError("need at least one argument")
        parts = self._parts
        drv = self._drv
        root = self._root
        if root:
            abs_parts = [drv, root] + parts[1:]
        else:
            abs_parts = parts
        to_drv, to_root, to_parts = self._parse_args(other)
        if to_root:
            to_abs_parts = [to_drv, to_root] + to_parts[1:]
        else:
            to_abs_parts = to_parts
        n = len(to_abs_parts)
        cf = self._flavour.casefold_parts
        if (root or drv) if n == 0 else cf(abs_parts[:n]) != cf(to_abs_parts):
            formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
>           raise ValueError("{!r} does not start with {!r}"
                             .format(str(self), str(formatted)))
E           ValueError: '/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/pydoctor/test/testpackages/basic/__init__.py' does not start with '/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0'

/usr/lib64/python3.8/pathlib.py:908: ValueError
========================================================================= short test summary info ==========================================================================
SKIPPED [1] pydoctor/test/test_model.py:293: cython_test_exception_raiser not installed
XFAIL pydoctor/test/test_epydoc2stan.py::test_func_arg_and_ret_annotation
XFAIL pydoctor/test/test_epydoc2stan.py::test_func_arg_and_ret_annotation_with_override
XFAIL pydoctor/test/test_epydoc2stan.py::test_func_arg_when_doc_missing
FAILED pydoctor/test/test_cyclic_imports_base_classes.py::test_cyclic_imports_base_classes - assert 1 == 0
FAILED pydoctor/test/test_model.py::test_htmlsourcetemplate_auto_detect - ValueError: '/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/pyt...
FAILED pydoctor/test/test_model.py::test_htmlsourcetemplate_custom - ValueError: '/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3....
===================================================== 3 failed, 720 passed, 1 skipped, 3 xfailed in 153.64s (0:02:33) ======================================================
```

**Comment by kloczek** [comment]
Looks like `--import-mode=importlib` is not needed however pytest still is failing in one unit because it accot find `pydoctor` nodule 🤔 
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-pydoctor-22.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0, configfile: setup.cfg, testpaths: pydoctor/test
plugins: hypothesis-6.41.0
collected 727 items

pydoctor/test/test_astbuilder.py ................................................................................................................................... [ 18%]
.................................................................................................................................................................... [ 40%]
..............                                                                                                                                                       [ 42%]
pydoctor/test/test_colorize.py .....                                                                                                                                 [ 43%]
pydoctor/test/test_commandline.py ..................                                                                                                                 [ 45%]
pydoctor/test/test_configparser.py ......                                                                                                                            [ 46%]
pydoctor/test/test_cyclic_imports_base_classes.py F                                                                                                                  [ 46%]
pydoctor/test/test_epydoc2stan.py ........xxx.......................................................                                                                 [ 55%]
pydoctor/test/test_model.py ..............s......                                                                                                                    [ 58%]
pydoctor/test/test_napoleon_docstring.py ......................................................                                                                      [ 66%]
pydoctor/test/test_napoleon_iterators.py .................                                                                                                           [ 68%]
pydoctor/test/test_node2stan.py .                                                                                                                                    [ 68%]
pydoctor/test/test_options.py .........                                                                                                                              [ 69%]
pydoctor/test/test_packages.py ............                                                                                                                          [ 71%]
pydoctor/test/test_qnmatch.py ......                                                                                                                                 [ 72%]
pydoctor/test/test_sphinx.py .............................                                                                                                           [ 76%]
pydoctor/test/test_templatewriter.py ................................                                                                                                [ 80%]
pydoctor/test/test_type_fields.py .........                                                                                                                          [ 81%]
pydoctor/test/test_utils.py ...............                                                                                                                          [ 83%]
pydoctor/test/test_zopeinterface.py .........................                                                                                                        [ 87%]
pydoctor/test/epydoc/epytext.doctest .                                                                                                                               [ 87%]
pydoctor/test/epydoc/restructuredtext.doctest .                                                                                                                      [ 87%]
pydoctor/test/epydoc/test_epytext.py ....                                                                                                                            [ 88%]
pydoctor/test/epydoc/test_epytext2html.py ...........                                                                                                                [ 89%]
pydoctor/test/epydoc/test_epytext2node.py .                                                                                                                          [ 89%]
pydoctor/test/epydoc/test_google_numpy.py .....                                                                                                                      [ 90%]
pydoctor/test/epydoc/test_parsed_docstrings.py .                                                                                                                     [ 90%]
pydoctor/test/epydoc/test_pyval_repr.py ..................................................                                                                           [ 97%]
pydoctor/test/epydoc/test_restructuredtext.py ..................                                                                                                     [100%]

================================================================================= FAILURES =================================================================================
_____________________________________________________________________ test_cyclic_imports_base_classes _____________________________________________________________________

    def test_cyclic_imports_base_classes() -> None:
        if sys.platform == 'win32':
            # Running this script with the following subprocess call fails on Windows
            # with an ImportError that isn't actually related to what we want to test.
            # So we just skip for Windows.
            return

        process = subprocess.Popen(
            [sys.executable, os.path.basename(__file__)],
            env={'PYTHONHASHSEED': '0'},
            cwd=os.path.dirname(__file__),
        )
>       assert process.wait() == 0
E       assert 1 == 0
E        +  where 1 = <bound method Popen.wait of <subprocess.Popen object at 0x7f3610b3bd30>>()
E        +    where <bound method Popen.wait of <subprocess.Popen object at 0x7f3610b3bd30>> = <subprocess.Popen object at 0x7f3610b3bd30>.wait

pydoctor/test/test_cyclic_imports_base_classes.py:22: AssertionError
--------------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cyclic_imports_base_classes.py", line 26, in <module>
    from test_packages import processPackage, model # type: ignore
  File "/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0/pydoctor/test/test_packages.py", line 5, in <module>
    from pydoctor import model
ModuleNotFoundError: No module named 'pydoctor'
========================================================================= short test summary info ==========================================================================
SKIPPED [1] pydoctor/test/test_model.py:293: cython_test_exception_raiser not installed
XFAIL pydoctor/test/test_epydoc2stan.py::test_func_arg_and_ret_annotation
XFAIL pydoctor/test/test_epydoc2stan.py::test_func_arg_and_ret_annotation_with_override
XFAIL pydoctor/test/test_epydoc2stan.py::test_func_arg_when_doc_missing
FAILED pydoctor/test/test_cyclic_imports_base_classes.py::test_cyclic_imports_base_classes - assert 1 == 0
=========================================================== 1 failed, 722 passed, 1 skipped, 3 xfailed in 22.64s ===========================================================
```

**Comment by tristanlatr** [comment]
Hi @kloczek, thanks for your interest into building `pydoctor` as a rpm package.

`pydoctor/test/test_cyclic_imports_base_classes.py` is a tricky test, you could just skip it while testing your rpm build. Maybe open a PR in which the test is skipped is a certain environment variable is set?

**Comment by kloczek** [comment]
> `pydoctor/test/test_cyclic_imports_base_classes.py` is a tricky test, you could just skip it while testing your rpm build.

That is what I've done so far 😄 

>  Maybe open a PR in which the test is skipped if a certain environment variable is set?

I'm not sure do I understand intention of that question🤔 
I'm skipping that test by use `--deselect pydoctor/test/test_cyclic_imports_base_classes.py::test_cyclic_imports_base_classes`.

**Comment by tristanlatr** [comment]
`--deselect pydoctor/test/test_cyclic_imports_base_classes.py::test_cyclic_imports_base_classes` sounds like a OK workaround, never mind.

**Comment by tristanlatr** [comment]
I’ll close this issue now, since this test is correctly running in our CI.
