### ISSUE TITLE
Generate Sphinx object inventory instead of pickle

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#75]
A pickle generated from https://twistedmatrix.com/trac/ticket/7018 can't then be loaded:

$ pydoctor --extra-system path/to/twisted/apidocs/system.pickle:https://twistedmatrix.com/documents/13.2.0/api/

Traceback (most recent call last):
  File "bin/pydoctor", line 12, in <module>
    sys.exit(main(sys.argv[1:]))
  File "lib/python2.7/site-packages/pydoctor/driver.py", line 261, in main
    moresystems.append(cPickle.load(open(fname, 'rb')))
  File "lib/python2.7/site-packages/pydoctor/model.py", line 463, in __setstate__
    n.append(lookup(vv))
  File "lib/python2.7/site-packages/pydoctor/model.py", line 446, in lookup
    raise KeyError, name
KeyError: 'twisted.internet.unix._SendmsgMixin 0._writeSomeDataBase'

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-03-04T01:18:38Z
 * owner: tom.prince
 * assignee: adiroiban
 * the launchpad url was https://bugs.launchpad.net/bugs/1287458

**Comment by mwhudson** [comment]
(by mwhudson)
So the fix here is (probably) to delete all the pickle-related code and switch to using sphinx's objects.inv format (this also means that we should be able to use the python.org objects.inv and delete the special casing for the standard library)

**Comment by mwhudson** [comment]
(by adiroiban)
I will try to work on this. Format for object inv is

# Sphinx inventory version 2
# Project: NAME
# Version: VERSION
# The remainder of this file is compressed with zlib.
ZLIB_COMPRESSED_CONTENT

content lines in the format
--------------------------------

name domainname:type priority uri dispname


Example
-------------

genindex std:label -1 genindex.html# Index
modindex std:label -1 py-modindex.html# Module Index
search std:label -1 search.html# Search Page

generate-uuid std:label -1 operation/command-line.html#$ Generating UUID
