### ISSUE TITLE
Can't use a custom --system-class (AttributeError)

### ISSUE THREAD

**Issue by ikalev** [twisted/pydoctor#92]
Using a custom subclass of ``pydoctor.twistedmodel.TwistedSystem``:

```
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\pydoctor\driver.py", line 390, in main
    writer.writeIndividualFiles(subjects, options.htmlfunctionpages)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\writer.py", line 43, in writeIndividualFiles
    self.writeDocsFor(ob, functionpages=functionpages)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\writer.py", line 68, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\writer.py", line 68, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\writer.py", line 68, in writeDocsFor
    self.writeDocsFor(o, functionpages)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\writer.py", line 65, in writeDocsFor
    self.writeDocsForOne(ob, f)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\writer.py", line 86, in writeDocsForOne
    flattenToFile(fobj, page)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\writer.py", line 19, in flattenToFile
    raise err[0]
twisted.web.error.FlattenerError: Exception while flattening:

  File "C:\Anaconda\lib\site-packages\twisted\web\_flatten.py", line 317, in _flattenTree
    element = stack[-1].next()
  File "C:\Anaconda\lib\site-packages\twisted\web\_flatten.py", line 240, in _flattenElement
    result = renderMethod(request, rootClone)
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\pages\__init__.py", line 159, in all
    heading=self.heading(),
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\pages\__init__.py", line 71, in heading
    tags.code(self.mediumName(self.ob)), " ",
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\pages\__init__.py", line 277, in mediumName
    r.append(taglink(o, n))
  File "C:\Anaconda\lib\site-packages\pydoctor\templatewriter\util.py", line 29, in taglink
    o.system.warning("html", "don't link to %s"%o.fullName())
AttributeError: 'MdSystem' object has no attribute 'warning'
```

Maybe ``link()`` and ``taglink()`` should be calling ``o.system.msg()`` instead of ``o.system.warning()``?

The implementation of ``MdSystem`` is:

```
class MdSystem(twistedmodel.TwistedSystem):

    def privacyClass(self, obj):
        o = obj

        while o:
            if o.name.startswith("_"):
                return model.PrivacyClass.HIDDEN
            if isinstance(o, model.Package) and o.name == 'test':
                return model.PrivacyClass.HIDDEN
            o = o.parent

        return super(MdSystem, self).privacyClass(obj)

    #def warning(self, *a, **k):
    #   return self.msg(*a, **k)
```

**Comment by adiroiban** [comment]
Thanks for the report.

Please note that in #105 there is a discussion about removing twistedmodel ....

Please send you feedback regarding why you need/want to use this model.

Maybe we should create a new WithHiddenPrivateAndTestsModel which can be used as a start.

**Comment by ikalev** [comment]
@adiroiban Removing this model is fine. The actual bug is in ``pydoctor.templatewriter.util``, not in the model. See my PR details: #111.
